#!/bin/bash
set -e

# Persist SSH host keys on the volume so they survive image redeploys.
# Host keys normally live in the image's /etc/ssh and are regenerated on every
# rebuild, which makes clients see a "REMOTE HOST IDENTIFICATION HAS CHANGED"
# warning after each redeploy. Keeping them on the mounted volume keeps the
# server identity stable across redeploys (it still changes on a node swap).
HOSTKEY_DIR=/home/dev/.ssh_host_keys
mkdir -p "$HOSTKEY_DIR"
[ -f "$HOSTKEY_DIR/ssh_host_ed25519_key" ] || ssh-keygen -t ed25519 -f "$HOSTKEY_DIR/ssh_host_ed25519_key" -N "" -q
[ -f "$HOSTKEY_DIR/ssh_host_rsa_key" ]     || ssh-keygen -t rsa -b 4096 -f "$HOSTKEY_DIR/ssh_host_rsa_key" -N "" -q
chmod 600 "$HOSTKEY_DIR"/*_key
chmod 644 "$HOSTKEY_DIR"/*_key.pub

# Refresh authorized_keys from env on every start (rotate via Coolify env + restart)
mkdir -p /home/dev/.ssh
echo "$AUTHORIZED_KEYS" > /home/dev/.ssh/authorized_keys
chown -R dev:dev /home/dev/.ssh
chmod 700 /home/dev/.ssh
chmod 600 /home/dev/.ssh/authorized_keys

# Ensure the volume-mounted home has correct ownership (first boot)
chown dev:dev /home/dev

# sshd does NOT pass the container's environment to login shells, so surface the
# workstation config to every SSH session via profile.d. (Sourced before the tmux
# auto-attach script, which reads these.)
{
  printf '# generated by entrypoint.sh — do not edit\n'
  printf 'export DEVBOX_PROJECT=%q\n'  "${DEVBOX_PROJECT:-}"
  printf 'export DEVBOX_DEV_CMD=%q\n'  "${DEVBOX_DEV_CMD:-}"
  printf 'export DEVBOX_DEV_PORT=%q\n' "${DEVBOX_DEV_PORT:-3000}"
  # The box's public dev URL (plain env var, matches the Domains field), so dev
  # servers can trust/use their own public origin (CORS, auth trusted-origins,
  # absolute URLs, ...). FQDN = URL minus scheme.
  printf 'export DEVBOX_URL=%q\n'      "${DEVBOX_URL:-}"
  printf 'export DEVBOX_FQDN=%q\n'     "$(printf '%s' "${DEVBOX_URL:-}" | sed -E 's#^[a-z]+://##; s#/.*$##')"
} > /etc/profile.d/00-devbox-env.sh

# Public dev-server preview: Caddy fronts container port 9009 -> the dev port.
# Auth: set DEVBOX_AUTH="user:password" to gate the URL with basic auth (hashed
# here at runtime, so no secret ever lives in git); leave it EMPTY to serve the
# URL public. A malformed value (no colon) disables the URL entirely — fail
# closed, never accidentally public. Caddy returns 502 until something listens
# on the dev port. Never let a proxy problem abort sshd — tolerate failure.
( set +e
  DEV_PORT="${DEVBOX_DEV_PORT:-3000}"
  AUTH_USER="" AUTH_HASH=""
  if [ -n "${DEVBOX_AUTH:-}" ]; then
    case "$DEVBOX_AUTH" in
      *:*)
        AUTH_USER="${DEVBOX_AUTH%%:*}"
        # --plaintext is required: stdin-piping errors with "EOF" (hash-password
        # wants an interactive confirm when reading from stdin). Verified caddy 2.x.
        AUTH_HASH="$(caddy hash-password --plaintext "${DEVBOX_AUTH#*:}")"
        [ -n "$AUTH_USER" ] && [ -n "$AUTH_HASH" ] || { echo "DEVBOX_AUTH: hashing failed"; exit 1; }
        ;;
      *) echo "DEVBOX_AUTH must be user:password — refusing to serve the dev URL"; exit 1;;
    esac
  fi
  mkdir -p /etc/caddy
  # printf (not a heredoc) so the '$' in the bcrypt hash is written literally.
  {
    printf '{\n\tadmin off\n\tauto_https off\n}\n:9009 {\n'
    if [ -n "$AUTH_HASH" ]; then
      printf '\tbasic_auth {\n\t\t%s %s\n\t}\n' "$AUTH_USER" "$AUTH_HASH"
    fi
    printf '\treverse_proxy 127.0.0.1:%s\n}\n' "$DEV_PORT"
  } > /etc/caddy/Caddyfile
  caddy start --config /etc/caddy/Caddyfile --adapter caddyfile
) || echo "warning: caddy proxy setup failed; public dev URL disabled (SSH + port-forward still work)"

exec /usr/sbin/sshd -D -e \
  -h "$HOSTKEY_DIR/ssh_host_ed25519_key" \
  -h "$HOSTKEY_DIR/ssh_host_rsa_key"
