#!/bin/bash
set -e

# Persist SSH host keys on the volume so they survive image redeploys.
# Host keys normally live in the image's /etc/ssh and are regenerated on every
# rebuild, which makes clients see a "REMOTE HOST IDENTIFICATION HAS CHANGED"
# warning after each redeploy. Keeping them on the mounted volume keeps the
# server identity stable across redeploys (it still changes on a node swap).
HOSTKEY_DIR=/home/dev/.ssh_host_keys
mkdir -p "$HOSTKEY_DIR"
[ -f "$HOSTKEY_DIR/ssh_host_ed25519_key" ] || ssh-keygen -t ed25519 -f "$HOSTKEY_DIR/ssh_host_ed25519_key" -N "" -q
[ -f "$HOSTKEY_DIR/ssh_host_rsa_key" ]     || ssh-keygen -t rsa -b 4096 -f "$HOSTKEY_DIR/ssh_host_rsa_key" -N "" -q
chmod 600 "$HOSTKEY_DIR"/*_key
chmod 644 "$HOSTKEY_DIR"/*_key.pub

# Refresh authorized_keys from env on every start (rotate via Coolify env + restart)
mkdir -p /home/dev/.ssh
echo "$AUTHORIZED_KEYS" > /home/dev/.ssh/authorized_keys
chown -R dev:dev /home/dev/.ssh
chmod 700 /home/dev/.ssh
chmod 600 /home/dev/.ssh/authorized_keys

# Ensure the volume-mounted home has correct ownership (first boot)
chown dev:dev /home/dev

# sshd does NOT pass the container's environment to login shells, so surface the
# workstation config to every SSH session via profile.d. (Sourced before the tmux
# auto-attach script, which reads these.)
{
  printf '# generated by entrypoint.sh — do not edit\n'
  printf 'export DEVBOX_PROJECT=%q\n'  "${DEVBOX_PROJECT:-}"
  printf 'export DEVBOX_DEV_CMD=%q\n'  "${DEVBOX_DEV_CMD:-}"
  printf 'export DEVBOX_DEV_PORT=%q\n' "${DEVBOX_DEV_PORT:-3000}"
} > /etc/profile.d/00-devbox-env.sh

# Public dev-server preview (optional): if a password is present, front the dev
# server with a Caddy basic-auth gate on 9009 -> the dev port. The password comes
# from Coolify (SERVICE_PASSWORD_DEVBOX) and is hashed here at runtime, so no secret
# ever lives in git. Skip it entirely when no password is set — port-forward still
# works. Caddy returns 502 until a dev server is actually listening on the dev port.
# Never let a proxy problem abort sshd — run the whole block tolerant of failure.
if [ -n "${SERVICE_PASSWORD_DEVBOX:-}" ]; then
  ( set +e
    DEV_USER="${SERVICE_USER_DEVBOX:-dev}"
    DEV_PORT="${DEVBOX_DEV_PORT:-3000}"
    # Pipe via stdin (no trailing newline) — version-stable across Caddy releases.
    HASH="$(printf '%s' "$SERVICE_PASSWORD_DEVBOX" | caddy hash-password)"
    mkdir -p /etc/caddy
    # printf (not a heredoc) so the '$' in the bcrypt hash is written literally.
    printf '{\n\tadmin off\n\tauto_https off\n}\n:9009 {\n\tbasic_auth {\n\t\t%s %s\n\t}\n\treverse_proxy 127.0.0.1:%s\n}\n' \
      "$DEV_USER" "$HASH" "$DEV_PORT" > /etc/caddy/Caddyfile
    caddy start --config /etc/caddy/Caddyfile --adapter caddyfile
  ) || echo "warning: caddy proxy setup failed; public dev URL disabled (SSH + port-forward still work)"
fi

exec /usr/sbin/sshd -D -e \
  -h "$HOSTKEY_DIR/ssh_host_ed25519_key" \
  -h "$HOSTKEY_DIR/ssh_host_rsa_key"
